version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - php

  php:
    build: .
    volumes:
      - ./:/code
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "park-lot"
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpasswd"
      MYSQL_ROOT_HOST: "%"
      LANG: "C.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  # set the  utf8 charset
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - mysql_db:/var/lib/
    tty: true

volumes:
  mysql_db:
    driver: local
